UADFV:
  enabled: true
  root: /home/asthanajee/Desktop/EE656/deepfake-detection-benchmark/datasets/UADFV/UADFV/UADFV
  manip_type: AEGAN
DF-TIMIT:
  enabled: true
  root: /home/asthanajee/Desktop/EE656/deepfake-detection-benchmark/datasets/DF-TIMIT/DF-TIMIT/DeepfakeTIMIT
  manip_type: AEGAN
Celeb-DF:
  enabled: true
  root: /home/asthanajee/Desktop/EE656/deepfake-detection-benchmark/datasets/Celeb-DF
  manip_type: AEGAN
DF-1.0:
  enabled: false
  root: DeeperForensics-1.0
  manip_type: AEGAN
FF++:
  enabled: true
  root: /home/asthanajee/Desktop/EE656/deepfake-detection-benchmark/datasets/FaceForensics++/FaceForensics++_C23
  manip_type: AEGAN
  methods: [DF, FS, FShifter]
DFDC:
  enabled: false
  root: DFDC
  manip_type: AEGAN
ForgeryNet:
  enabled: true
  root: /home/asthanajee/Desktop/EE656/deepfake-detection-benchmark/datasets/ForgeryNet/ForgeryNet/imgs
  manip_type: Graphic
CelebA:
  enabled: false
  root: CelebA
  manip_type: AEGAN
